### ISSUE TITLE
Please provide a descriptive title of your question

### ISSUE THREAD

**Issue by BeauPetite** [zachgoll/fullstack-roadmap-series#2]
_This is a Github issue template.  You will need to replace all lines marked with **REPLACE**.  If you want to see an example issue, [please refer to this one](https://github.com/zachgoll/fullstack-roadmap-series/issues/1).  While I will try to get to your question as quickly as possible, I am creating this series for free and therefore don't always have a ton of free time.  Thanks for your understanding!_

### What video or post URL is your question regarding?

[Write Your First JavaScript Program #fullstackroadmap (Ep. 1)](https://www.youtube.com/watch?v=XWS5w5eQzFk&list=PLYQSCk-qyTW37zDPzcAyzCsnypFQrhUcq&index=2)

### If it is a YouTube video, what timestamp are you asking about?

6:10

### What is your question?

When you hit enter, after inserted the dog image into the html code, your page automatically updated, reflecting the changes you made.  However, when I insert a link to the new graphic and hit enter nothing happens.

I can see the change has been made in the code, but it doesn't actually reflect the changes in the browser.

**Comment by BeauPetite** [comment]
I found the problem. 

I changed the src="image_link.png"

however, i didn't change the <source srcset="/lgogos/dootle"

After I changed that it worked.

**Comment by zachgoll** [comment]
Hey @BeauPetite, thanks for watching the series and taking the time to fill out the issue template!  Glad you figured it out :+1:

**Comment by BeauPetite** [comment]
Thanks for hitting me back. 

Although I solved the issue the first time, it came back to haunt me in the first Java Coding lesson, as you basically do the same thing only using the scripting language.  Unfortunately I wasn't able to figure out how to modify the code to change the <source srcset> to make it work.

If possible you might add an addendum for that.

FYI: Firefox Developer Edition Browser version 95.0b5(64 bit) on MacOS Monterey
