### ISSUE TITLE
Please provide a descriptive title of your question

### ISSUE THREAD

**Issue by BeauPetite** [zachgoll/fullstack-roadmap-series#3]
_This is a Github issue template.  You will need to replace all lines marked with **REPLACE**.  If you want to see an example issue, [please refer to this one](https://github.com/zachgoll/fullstack-roadmap-series/issues/1).  While I will try to get to your question as quickly as possible, I am creating this series for free and therefore don't always have a ton of free time.  Thanks for your understanding!_

### What video or post URL is your question regarding?

[5 Beginner JavaScript Coding Challenges](https://www.youtube.com/watch?v=caz6eZSvktI&list=PLYQSCk-qyTW37zDPzcAyzCsnypFQrhUcq&index=9)
### If it is a YouTube video, what timestamp are you asking about?

1:22

### What is your question?

The code for "Challenge 2" is actually exactly the same.
<img width="998" alt="Challenge-2" src="https://user-images.githubusercontent.com/79995193/141533291-388d68a0-4add-48b9-a3d7-2e9a78e527c4.png">

**Comment by zachgoll** [comment]
Sorry, just seeing this now!  Great catch, will update!
